# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AskMaster < Formula
  desc "Physical Human-in-the-Loop MCP server for AI coding agents using M5Stack Cardputer"
  homepage "https://github.com/mhrsntrk/ask-master"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhrsntrk/ask-master/releases/download/v1.1.0/ask-master_1.1.0_darwin_amd64.tar.gz"
      sha256 "b6f2793da971f4bbd53c0b22cf1dece4bda19f33a93c06b7fa7add0283e32610"

      define_method(:install) do
        bin.install "ask-master"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mhrsntrk/ask-master/releases/download/v1.1.0/ask-master_1.1.0_darwin_arm64.tar.gz"
      sha256 "70df779e819f4ae755c469ebb6d6e097d26ae309275751e0016136aa89db67e2"

      define_method(:install) do
        bin.install "ask-master"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mhrsntrk/ask-master/releases/download/v1.1.0/ask-master_1.1.0_linux_amd64.tar.gz"
      sha256 "0963778dc489eaac52045044fa64862439b0c01a0c63bfcc7a6c9b91a04d43dc"
      define_method(:install) do
        bin.install "ask-master"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mhrsntrk/ask-master/releases/download/v1.1.0/ask-master_1.1.0_linux_arm64.tar.gz"
      sha256 "7397482e8179434de25377cf28192189008a0005b01a814479a55e913c42ada8"
      define_method(:install) do
        bin.install "ask-master"
      end
    end
  end

  test do
    system "#{bin}/ask-master", "--version"
  end
end
