# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AskMaster < Formula
  desc "Physical Human-in-the-Loop MCP server for AI coding agents using M5Stack Cardputer"
  homepage "https://github.com/mhrsntrk/ask-master"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhrsntrk/ask-master/releases/download/v1.1.0/ask-master_1.1.0_darwin_amd64.tar.gz"
      sha256 "1f091a06116ce3b3d83cd9eb47049d11a8ac8d40ee30af46cf75e084e5b1f58e"

      define_method(:install) do
        bin.install "ask-master"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mhrsntrk/ask-master/releases/download/v1.1.0/ask-master_1.1.0_darwin_arm64.tar.gz"
      sha256 "9dda5ad0342a956cccd8c1c17d6c3c73d7228b3ca8a22803d3524f3cce002947"

      define_method(:install) do
        bin.install "ask-master"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mhrsntrk/ask-master/releases/download/v1.1.0/ask-master_1.1.0_linux_amd64.tar.gz"
      sha256 "b220f90604a7adda6c87db057795ab2d1432bc9f8d44f157de431f253cccf0cf"
      define_method(:install) do
        bin.install "ask-master"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mhrsntrk/ask-master/releases/download/v1.1.0/ask-master_1.1.0_linux_arm64.tar.gz"
      sha256 "fe3de114f991eb22bab0911b43f573d33acfa747fde65e8fde8dd18d87b5060b"
      define_method(:install) do
        bin.install "ask-master"
      end
    end
  end

  test do
    system "#{bin}/ask-master", "--version"
  end
end
